apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    enviroment: test
  name: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      enviroment: test
  minReadySeconds: 10
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        enviroment: test
    spec:
      containers:
      - image: nginx:1.16
        name: nginx