{{- range $user := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # moved from ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: {{ $user }}-apps # user-argo ns role binding is applied directly with manifests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-server
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: {{ $user }}-argo
{{- end }}
