{{- range $user := .Values.users }}
{{- range $suffix := $.Values.namespacesuffixes }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $user }}-{{ $suffix }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    helm.sh/hook-weight: "10"
{{- end }}
{{- end }}
