namespace: olek-argo 

commonAnnotations:
  created-by: olek

resources:
#- ClusterRole_argocd-application-controller.yaml
- ConfigMap_argocd-cmd-params-cm.yaml
#- ClusterRoleBinding_argocd-server.yaml
#- ClusterRoleBinding_argocd-application-controller.yaml
#- ClusterRole_argocd-server.yaml
- ConfigMap_argocd-rbac-cm.yaml
- ConfigMap_argocd-notifications-cm.yaml
- ConfigMap_argocd-gpg-keys-cm.yaml
- ConfigMap_argocd-cm.yaml
#- CustomResourceDefinition_applications.argoproj.io.yaml
- ConfigMap_argocd-tls-certs-cm.yaml
- ConfigMap_argocd-ssh-known-hosts-cm.yaml
#- CustomResourceDefinition_appprojects.argoproj.io.yaml
#- CustomResourceDefinition_applicationsets.argoproj.io.yaml
- Deployment_argocd-notifications-controller.yaml
- Deployment_argocd-dex-server.yaml
- Deployment_argocd-applicationset-controller.yaml
- NetworkPolicy_argocd-application-controller-network-policy.yaml
- Deployment_argocd-server.yaml
- Deployment_argocd-repo-server.yaml
- Deployment_argocd-redis.yaml
- NetworkPolicy_argocd-repo-server-network-policy.yaml
- NetworkPolicy_argocd-redis-network-policy.yaml
- NetworkPolicy_argocd-dex-server-network-policy.yaml
- Role_argocd-dex-server.yaml
- Role_argocd-applicationset-controller.yaml
- Role_argocd-application-controller.yaml
- NetworkPolicy_argocd-server-network-policy.yaml
- RoleBinding_argocd-applicationset-controller.yaml
- RoleBinding_argocd-application-controller.yaml
- Role_argocd-server.yaml
- Role_argocd-notifications-controller.yaml
- RoleBinding_argocd-server.yaml
- RoleBinding_argocd-redis.yaml
- RoleBinding_argocd-notifications-controller.yaml
- RoleBinding_argocd-dex-server.yaml
- ServiceAccount_argocd-dex-server.yaml
- ServiceAccount_argocd-applicationset-controller.yaml
- ServiceAccount_argocd-application-controller.yaml
- Secret_argocd-secret.yaml
- Secret_argocd-notifications-secret.yaml
- Service_argocd-applicationset-controller.yaml
- ServiceAccount_argocd-server.yaml
- ServiceAccount_argocd-redis.yaml
- ServiceAccount_argocd-notifications-controller.yaml
- Service_argocd-repo-server.yaml
- Service_argocd-redis.yaml
- Service_argocd-notifications-controller-metrics.yaml
- Service_argocd-metrics.yaml
- Service_argocd-dex-server.yaml
- StatefulSet_argocd-application-controller.yaml
- Service_argocd-server.yaml
- Service_argocd-server-metrics.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: olek-argo
  target:
    kind: ClusterRoleBinding
    name: argocd-server
    group: rbac.authorization.k8s.io
    version: v1
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: olek-argo
  target:
    kind: ClusterRoleBinding
    name: argocd-application-controller
    group: rbac.authorization.k8s.io
    version: v1

