apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer-perf
spec:
  volumes:
    - name: config-volume
      configMap:
        name: kafka-producer-config
        items:
          - key: producer.properties
            path: producer.properties
  containers:
    - name: kafka-producer-perf
      image: quay.io/strimzi/kafka:0.40.0-kafka-3.6.1
      command: ["bin/kafka-producer-perf-test.sh"]
      args: ["--topic", "perf-test", "--num-records", "3000000", "--throughput", "-1", "--record-size", "1024", "--producer.config", "/etc/kafka/producer.properties"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/kafka
  restartPolicy: Never
