apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 3.6.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32200
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: '3.6'
      min.insync.replicas: 1
      num.network.threads: 1
      num.partitions: 5
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      class: ocs-storagecluster-ceph-rbd
      size: 10Gi
      type: persistent-claim
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: ocs-storagecluster-ceph-rbd
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics.yaml
  entityOperator:
    topicOperator: {}
    userOperator: {}