{{- range $user := .Values.users }}
{{- range $suffix := $.Values.namespacesuffixes }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: {{ $user }}-{{ $suffix }}
subjects:
- kind: ServiceAccount
  name: {{ $user }}
  namespace: default
roleRef:
  kind: Role
  name: ns-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-manager-role-binding
  namespace: {{ $user }}-{{ $suffix }}
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: {{ $user }}-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-role
{{- end }}
{{- end }}
