{{- range $user := .Values.users }}
{{- range $suffix := $.Values.namespacesuffixes }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-admin
  namespace: {{ $user }}-{{ $suffix }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
{{- end }}
{{- end }}
