{{- range .Values.users }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: {{ . }}-argo
{{- end }}