apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: httpd
  namespace: poligon
spec:
  containers:
    - name: httpd
      image: 'mcovglobal.azurecr.io/mcov-pl/devops/php-login-site:latest'
      ports:
        - containerPort: 8080
  imagePullSecrets:
  - name: acr-secret
